version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/hello_rails # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/ruby:2.6.5-node # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          APP_DATABASE_USERNAME: postgres
          APP_DATABASE_PASSWORD: password
          APP_DATABASE_HOST: 127.0.0.1
          APP_DATABASE_PORT: 5432
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine # database image
        environment: # environment variables for database
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: "password"
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Mecab導入時はコメントアウトを外してください（Dockerfileも要修正）
      # - run:
      #     name: Install Mecab
      #     command: |
      #       sudo apt-get update;
      #       sudo apt-get -y install libmecab2 libmecab-dev mecab mecab-ipadic mecab-ipadic-utf8 mecab-utils

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: npm Install
          command: npm install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: |
            bundle exec rake spec