name: Rails Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13.6
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-v4-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-v3-
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Yarn Install
      run: |
        yarn install
    - name: Build and test with Rake
      env:
        APP_DATABASE_USERNAME: postgres
        APP_DATABASE_PASSWORD: password
        APP_DATABASE_HOST: 127.0.0.1
        APP_DATABASE_PORT: 5432
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle config build.sassc --disable-march-tune-native
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:schema:load --trace
        bundle exec rake spec
